### ISSUE TITLE
After Installation: Error: Cannot find module '../vendor'

### ISSUE THREAD

**Issue by maxdobler** [arabsight/aurelia-mdl-plugin#2]
after npm installation this error pops up when I type "ai"...
I have newest Ubuntu OS

module.js:442
    throw err;
    ^

Error: Cannot find module '../vendor'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/aurelia-installer/lib/commands/bundle/unbundle.js:15:30)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by arabsight** [comment]
I believe that's an aurelia-installer error that has nothing to do with the plugin. the only thing that I tried to do with aurelia-installer is (ai init) and it gave me the same error so I didn't try again.

**Comment by maxdobler** [comment]
Oh sorry, this was the wrong github page...  :O
